spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/course_db_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    sharding:
      # 没有规则的表，默认去找ds0
      default-data-source-name: ds0
      tables:
        course:
          # 指定course表分布情况，表名称是什么
          actual-data-nodes: ds0.course_$->{1..2}
          # 表主键的生成策略，雪花算法
          key-generator:
            column: id
            type: SNOWFLAKE
          # 分片策略，约定id值为偶数添加到course_1表，奇数添加为course_2表
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: course_$->{id % 2 + 1}
        t_user:
          actual-data-nodes: ds1.t_user
          key-generator:
            column: user_id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: t_user
        t_udict:
          key-genetator:
            column: dict_id
            type: SNOWFLAKE
      # 公共表的配置
      broadcast-tables: t_udict

    # 打开sql输出日志
    props:
      sql:
        show: true
  # 一个实体对应两张表，覆盖
  main:
    allow-bean-definition-overriding: true
